export const dummyTransactionData = [
    {
        transactionType: 'Travelling',
        location: 'New York',
        amount: '$20.00',
        status: 'Failed',
        date: '06-02-2024',
        time: '9:23am',
        transactionID: 'R3487',
        action: 'Open',
        color: 'red',
    },
    {
        transactionType: 'Travelling',
        location: 'London',
        amount: '$40.00',
        status: 'pending',
        date: '06-02-2024',
        time: '10:23pm',
        transactionID: 'R3488',
        action: 'Open',
        color: 'orange'
    },
    {
        transactionType: 'Travelling',
        location: 'New Jersey',
        amount: '$10.00',
        status: 'Success',
        date: '06-02-2024',
        time: '8:30am',
        transactionID: 'R3489',
        action: 'Open',
        color: 'green'
    },
    {
        transactionType: 'Travelling',
        location: 'Berlin',
        amount: '$80.00',
        status: 'Success',
        date: '06-02-2024',
        time: '9:52pm',
        transactionID: 'R3490',
        action: 'Open',
        color: 'green',
    },
    {
        transactionType: 'Travelling',
        location: 'Nigeria',
        amount: '$20.00',
        status: 'Failed',
        date: '06-02-2024',
        time: '7:30am',
        transactionID: 'R3491',
        action: 'Open',
        color: 'red'
    },
    {
        transactionType: 'Travelling',
        location: 'London',
        amount: '$40.00',
        status: 'pending',
        date: '06-02-2024',
        time: '10:23pm',
        transactionID: 'R3492',
        action: 'Open',
        color: 'orange'
    },
    {
        transactionType: 'Travelling',
        location: 'London',
        amount: '$40.00',
        status: 'pending',
        date: '06-02-2024',
        time: '10:23pm',
        transactionID: 'R3493',
        action: 'Open',
        color: 'orange'
    },
    {
        transactionType: 'Travelling',
        location: 'Berlin',
        amount: '$80.00',
        status: 'Success',
        date: '06-02-2024',
        time: '9:52pm',
        transactionID: 'R3494',
        action: 'Open',
        color: 'green',
    },
    {
        transactionType: 'Travelling',
        location: 'Berlin',
        amount: '$80.00',
        status: 'Success',
        date: '06-02-2024',
        time: '9:52pm',
        transactionID: 'R3495',
        action: 'Open',
        color: 'green',
    },
    {
        transactionType: 'Travelling',
        location: 'New York',
        amount: '$20.00',
        status: 'Failed',
        date: '06-02-2024',
        time: '9:23am',
        transactionID: 'R3496',
        action: 'Open',
        color: 'red',
    },
]